
export const chats = [
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 1",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 2",
        _id: "2",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "2",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 3",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 4",
        _id: "4",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "4",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 5",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 6",
        _id: "6",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "6",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 5",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 6",
        _id: "6",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "6",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 5",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 6",
        _id: "6",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "6",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 5",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 6",
        _id: "6",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "6",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: ["https://images.unsplash.com/photo-1557296387-5358ad7997bb?q=80&w=1957&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        name: "Chat 5",
        _id: "1",
        groupChat: false,
        sameSender: false,
        isOnline: true,
        newMessagesAlert: {
            chatId: "1",
            count: 0,
        },
        members: ["1","2"],
        index: 0,
        handleDeleteChatOpen: () => {},
    },
    {
        avatar: [],
        name: "Chat 6",
        _id: "6",
        groupChat: false,
        sameSender: true,
        isOnline: false,
        newMessagesAlert: {
            chatId: "6",
            count: 0,
        },
        members: ["2","3"],
        index: 1,
        handleDeleteChatOpen: () => {},
    },
]